[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run db:migrate:deploy && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production" 